name: Continuous Deployment
 
on: 
  push:
    branches:
      - master
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: SSH and deploy app
      uses: appleboy/ssh-action@master
      with:
        # host: localhost
        # username: postgres
        # password: if0balino
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          git pull origin master
          npm install
          npm run migrate up
          npm run start
